cargo-features = ["strip"]

[package]
name = "handlematters"
version = "0.2.0"
edition = "2021"
description = "Self-contained template system with Handlebars and inline shell scripts"
authors = ["Keita Urashima <ursm@ursm.jp>"]
license = "MIT"

[dependencies]
anyhow = "1.0.48"
clap = { version = "3.0.0", features = ["derive"] }
handlebars = "4.1.5"
indoc = "1.0.3"
serde_yaml = "0.8.21"

[dev-dependencies]
assert_cmd = "2.0.2"
predicates = "2.1.0"
tempfile = "3.2.0"

[profile.release]
codegen-units = 1
lto = true
strip = "symbols"

[features]
